version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=Asdf4321
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1
volumes:
  db:
    driver: local
